version: "3.3"
services:
  nezha-agent:
    container_name: nezha-agent
    environment:
      - SERVER=${DASHBOARD_DOMAIN}
      - CLIENT_SECRET=${SECRET}
      - UUID=${UUID}
    image: kuusei/nezha-agent:v1.9.5
    restart: unless-stopped
    network_mode: host
networks: {}
