# layer 1
FROM golang:latest as build-stage

WORKDIR /app
COPY . .

RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o screen-studio-register-api

# layer 2
FROM scratch as runtime-stage

COPY --from=build-stage /app/screen-studio-register-api /screen-studio-register-api

EXPOSE 8080
CMD ["./screen-studio-register-api"]
