name: Docker Image Build nezha_agent_docker_build

on:
  push:
    branches:
      - 'main'
    paths:
      - 'nezha-agent/**'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      # Fetch the latest Nezha Agent release version
      - name: Check for Nezha Agent updates
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/nezhahq/agent/releases/latest | jq -r '.tag_name')
          if [[ -z "$LATEST_VERSION" ]]; then
            echo "Failed to get latest version" >&2
            exit 1
          fi
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
          echo "LATEST_VERSION is $LATEST_VERSION"

      # Build and push the multi-architecture Docker image
      - name: Build and push multi-arch Docker image
        working-directory: nezha-agent
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            --build-arg VERSION=${{ env.LATEST_VERSION }} \
            --tag kuusei/nezha-agent:${{ env.LATEST_VERSION }} \
            --tag kuusei/nezha-agent:latest \
            --push \
            .